
package login;

import cNegocio.UserService;


public class RegisterWindow extends javax.swing.JPanel {
    private UserService userService;
   
    /**
     * Creates new form RegisterWindows
     */
    public RegisterWindow() {
        initComponents();
        userService = new UserService();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCardHeader = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtPassContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCardHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Header.jpg"))); // NOI18N
        lblCardHeader.setText("jLabel2");
        lblCardHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblCardHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 370, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 370, 30));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContraseña.setText("Contraseña");
        add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        add(txtPassContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 370, 30));

        btnRegistrar.setBackground(new java.awt.Color(85, 110, 230));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 370, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String username = txtUsername.getText();
        String email = txtEmail.getText();
        String password = new String(txtPassContraseña.getPassword());
        if (userService.register(username, email, password)) {
            // Registro exitoso, mostrar mensaje de bienvenida
        } else {
            // Registro fallido, mostrar mensaje de error
        }
    
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCardHeader;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassContraseña;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
