
package cPresentacion;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        InitContent();
    }
    
    private void InitContent(){
        ShowJPanel(new RegistroMatricula());
        
    }
    
    private void ShowJPanel(JPanel rm){
        rm.setSize(700, 550);
        rm.setLocation(0,0);
        
        content.removeAll();
        content.add(rm, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        lblTitleMatricula = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistroMatricula1 = new javax.swing.JButton();
        btnRegistroNotas = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(51, 51, 255));
        menu.setPreferredSize(new java.awt.Dimension(200, 550));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleMatricula.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTitleMatricula.setText("MATRICULA");
        menu.add(lblTitleMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 83, 160, 10));

        btnRegistroMatricula1.setText("REGISTRAR MATRICULA");
        btnRegistroMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroMatricula1ActionPerformed(evt);
            }
        });
        menu.add(btnRegistroMatricula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        btnRegistroNotas.setText("REGISTRAR NOTAS");
        btnRegistroNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroNotasActionPerformed(evt);
            }
        });
        menu.add(btnRegistroNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        content.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMatricula1ActionPerformed
        ShowJPanel(new RegistroMatricula());
    }//GEN-LAST:event_btnRegistroMatricula1ActionPerformed

    private void btnRegistroNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroNotasActionPerformed
        ShowJPanel(new RegistroNotas());
    }//GEN-LAST:event_btnRegistroNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroMatricula1;
    private javax.swing.JButton btnRegistroNotas;
    private javax.swing.JPanel content;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitleMatricula;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
