
package cPresentacion;

import Entidad.Nota;
import cNegocio.NotaNegocio;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class RegistroNotas extends javax.swing.JPanel {

    private NotaNegocio notaNegocio;
    /**
     * Creates new form RegistroNotas
     */
    public RegistroNotas() {
        initComponents();
        notaNegocio = new NotaNegocio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitleRegistroNotas = new javax.swing.JLabel();
        lblDniAlumno = new javax.swing.JLabel();
        txtDniAlumno = new javax.swing.JTextField();
        lblCurso = new javax.swing.JLabel();
        cboxCurso = new javax.swing.JComboBox<>();
        lblNota1 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        lblNota2 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        lblNota3 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        lblPromedioFinal = new javax.swing.JLabel();
        txtPromedioFinal = new javax.swing.JTextField();
        btnRegistrarNota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotas = new javax.swing.JTable();

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleRegistroNotas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitleRegistroNotas.setText("REGISTRO DE NOTAS");
        background.add(lblTitleRegistroNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblDniAlumno.setText("DNI del alumno");
        background.add(lblDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        background.add(txtDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 30));

        lblCurso.setText("Curso:");
        background.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        cboxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas operativos", "Taller de programación web", "Algoritmos y estructuras de datos", "Redes y comunicación de datos I", " " }));
        background.add(cboxCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 250, 30));

        lblNota1.setText("Nota 1:");
        background.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        background.add(txtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 180, 30));

        lblNota2.setText("Nota 2:");
        background.add(lblNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        background.add(txtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, 30));

        lblNota3.setText("Nota 3:");
        background.add(lblNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        background.add(txtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, 30));

        lblPromedioFinal.setText("Promedio final:");
        background.add(lblPromedioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));
        background.add(txtPromedioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, 30));

        btnRegistrarNota.setText("REGISTRAR");
        btnRegistrarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNotaActionPerformed(evt);
            }
        });
        background.add(btnRegistrarNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 150, 30));

        tableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "dni", "curso", "nota 1", "nota 2", "nota 3", "promedio final"
            }
        ));
        jScrollPane1.setViewportView(tableNotas);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 680, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void cargarDatosTabla() {
        List<Nota> notas = notaNegocio.obtenerNotas();
        DefaultTableModel modelo = (DefaultTableModel) tableNotas.getModel();
        modelo.setRowCount(0); // Limpiar la tabla
        for (Nota nota : notas) {
            modelo.addRow(new Object[]{nota.getDniAlumno(), nota.getCurso(), nota.getNota1(), nota.getNota2(), nota.getNota3(), nota.getPromedioFinal()});
        }
    }
    
    private void btnRegistrarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotaActionPerformed
        Nota nota = new Nota();
        nota.setDniAlumno(txtDniAlumno.getText());
        nota.setCurso((String) cboxCurso.getSelectedItem());
        nota.setNota1(Double.parseDouble(txtNota1.getText()));
        nota.setNota2(Double.parseDouble(txtNota2.getText()));
        nota.setNota3(Double.parseDouble(txtNota3.getText()));
        nota.setPromedioFinal(Double.parseDouble(txtPromedioFinal.getText()));
        notaNegocio.registrarNota(nota);
        // Actualizar la tabla con la nueva nota registrada
        DefaultTableModel modelo = (DefaultTableModel) tableNotas.getModel();
        modelo.addRow(new Object[]{nota.getDniAlumno(), nota.getCurso(), nota.getNota1(), nota.getNota2(), nota.getNota3(), nota.getPromedioFinal()});
    }//GEN-LAST:event_btnRegistrarNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrarNota;
    private javax.swing.JComboBox<String> cboxCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDniAlumno;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblPromedioFinal;
    private javax.swing.JLabel lblTitleRegistroNotas;
    private javax.swing.JTable tableNotas;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtPromedioFinal;
    // End of variables declaration//GEN-END:variables
}
